name: Deploy Application

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Run your tests here (for example, pytest)
        pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      run: |
        curl -X POST https://api.render.com/deploy/srv-crmsr908fa8c73ao7f20?key=zxUBgAQ3xNk
